// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhK1p8wTFP-0Ew2r3VSZ3PLRfxfMGiXsg',
    appId: '1:928387666470:web:b991763cefc9c39f7e8ce7',
    messagingSenderId: '928387666470',
    projectId: 'hpu-edhub',
    authDomain: 'hpu-edhub.firebaseapp.com',
    storageBucket: 'hpu-edhub.firebasestorage.app',
    measurementId: 'G-T9SP1TS1EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0oby7skio-9YIATVQ2poI7oIi1Uak7Bo',
    appId: '1:928387666470:android:f69d7af1419b9d2f7e8ce7',
    messagingSenderId: '928387666470',
    projectId: 'hpu-edhub',
    storageBucket: 'hpu-edhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-U5Q2S1TtFsU1fdLpv9EzcEQKnMcS74',
    appId: '1:928387666470:ios:30289a42d88cccdb7e8ce7',
    messagingSenderId: '928387666470',
    projectId: 'hpu-edhub',
    storageBucket: 'hpu-edhub.firebasestorage.app',
    iosBundleId: 'com.example.hpuEduhust',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI-U5Q2S1TtFsU1fdLpv9EzcEQKnMcS74',
    appId: '1:928387666470:ios:30289a42d88cccdb7e8ce7',
    messagingSenderId: '928387666470',
    projectId: 'hpu-edhub',
    storageBucket: 'hpu-edhub.firebasestorage.app',
    iosBundleId: 'com.example.hpuEduhust',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhK1p8wTFP-0Ew2r3VSZ3PLRfxfMGiXsg',
    appId: '1:928387666470:web:f12fcc80e7f0e7987e8ce7',
    messagingSenderId: '928387666470',
    projectId: 'hpu-edhub',
    authDomain: 'hpu-edhub.firebaseapp.com',
    storageBucket: 'hpu-edhub.firebasestorage.app',
    measurementId: 'G-6HJBMBQPX9',
  );
}
